import type { Metadata } from "next";
import "./globals.css";
import { Alegreya } from 'next/font/google'
import NavMain from "./components/NavMain";

const fontSerif = Alegreya({
  subsets: ['latin'],
  variable: '--font-serif',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={fontSerif.className}>
      <body
        className="w-full h-dvh min-h-dvh font-serif bg-stone-100"
      >
        <NavMain></NavMain>
        {children}
      </body>
    </html>
  );
}
