import type { Metadata } from "next";
import "./globals.css";
import NavMain from "./components/NavMain";
import { Noto_Sans, Roboto_Mono, Literata } from 'next/font/google';
 
const sans = Noto_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-sans',
})

const serif = Literata({
  subsets: ['latin'],
  display: 'optional',
  variable: '--font-serif',
})
 
const mono = Roboto_Mono({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-mono',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${sans.variable} ${serif.variable} ${mono.variable}`}>
      <body 
        className="relative w-full h-dvh min-h-dvh font-serif bg-paper-texture"
      >
        <NavMain></NavMain>
        {children}
      </body>
    </html>
  );
}
